#!/usr/bin/env python3

################################################################################
# Copyright (c) 2023 fxzjshm
# This software is licensed under Mulan PubL v2.
# You can use this software according to the terms and conditions of the Mulan PubL v2.
# You may obtain a copy of Mulan PubL v2 at:
#          http://license.coscl.org.cn/MulanPubL-2.0
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PubL v2 for more details.
################################################################################

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import argparse

def main():
    '''
    simple helper script to plot spectrum generated by the main program simple-radio-telescope-backend
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument("file_path")
    parser.add_argument("--zoom_x", required=False, default=1)
    parser.add_argument("--zoom_y", required=False, default=1/8)
    args = parser.parse_args()
    file_path = args.file_path
    zoom_x = float(args.zoom_x)
    zoom_y = float(args.zoom_y)

    mpl.use("TkAgg")
    print("matplotlib backend = ", mpl.get_backend())

    spec_complex = np.load(file_path)
    print("spec_complex.dtype = ", spec_complex.dtype)
    print("spec_complex.shape = ", spec_complex.shape)
    # before 9bcd183 shape is incorrect
    #spec_complex.shape = ((spec_complex.shape[1], spec_complex.shape[0]))
    print("spec_complex.shape = ", spec_complex.shape)
    spec_real = (np.abs(spec_complex)**2)
    del spec_complex
    zoomed_x = int(spec_real.shape[1] * zoom_x)
    spec_zoomed_x = spec_real.reshape(-1, zoomed_x, spec_real.shape[1] // zoomed_x).sum(axis=2)
    zoomed_y = int(spec_real.shape[0] * zoom_y)
    spec_zoomed = spec_zoomed_x.reshape(-1, spec_real.shape[0] // zoomed_y, zoomed_x).sum(axis=1)
    print("spec_zoomed.shape = ", spec_zoomed.shape)
    del spec_real
    spec_average = np.average(spec_zoomed)
    print("avg = ", spec_average)

    time_series = np.sum(spec_zoomed, axis=0)
    time_series_average = np.average(time_series);
    time_series -= time_series_average
    print("time_series.shape = ", time_series.shape)

    freq_dist = np.sum(spec_zoomed, axis=1)
    print("freq_dist.shape = ", freq_dist.shape)

    mpl.rcParams['agg.path.chunksize'] = 10000
    # https://stackoverflow.com/questions/42973223/how-to-share-x-axes-of-two-subplots-after-they-have-been-created
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, gridspec_kw={'width_ratios': [3, 1], 'height_ratios': [3, 1]})
    ax1.get_shared_x_axes().join(ax1, ax3)
    ax1.get_shared_y_axes().join(ax1, ax2)
    ax1.pcolormesh(spec_zoomed, vmin=0.0, vmax=10*spec_average)
    ax2.plot(freq_dist, np.array(range(freq_dist.shape[0])))
    ax3.plot(time_series)
    plt.show()

if __name__ == '__main__':
    main()
